# Site settings
title: Ben Cohen
email: 
description: "The online portfolio for Ben Cohen."
baseurl: ""
url: "http://brianzelip.github.io/cohen"

# Build settings
markdown: kramdown
permalink: pretty
